[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ie_utils"
author = "Daniel Victoria López"
author-email = "daniel.victoria@student.ie.edu"
description-file = "README.md"

